name: Backfill NFL history

permissions:
  contents: write

on:
  workflow_dispatch: {}

jobs:
  backfill:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backfill
        env:
          SPORTSDATAIO_KEY: ${{ secrets.SPORTSDATAIO_KEY }}
        run: |
          python src/backfill_history.py

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Contenido de data/:"
          ls -la data || true

          if [ -f data/historical_games.csv ]; then
            echo "Filas en CSV (incluye cabecera): $(wc -l < data/historical_games.csv)"
          else
            echo "ERROR: data/historical_games.csv no fue creado por el backfill."
            exit 1
          fi

          # Staggea SIEMPRE el archivo (incluye caso 'untracked')
          git add -A data/historical_games.csv

          # Commit solo si hay algo staged que commitear
          if git diff --cached --quiet; then
            echo "No hay cambios que commitear."
          else
            echo "Hay cambios. Haciendo commit/push..."
            git commit -m "feat(data): backfill 2022-2024 NFL finals"
            git pull --rebase
            git push
          fi
