name: NFL Picks to Telegram

on:
  schedule:
    # TNF: Jueves 09:00 Tijuana (UTC-7/-8) → 16:00 UTC
    - cron: "0 16 * * 4"
    # Weekend: Sábado 20:00 Tijuana.
    # Durante horario de verano Tijuana ≈ UTC-7 → 20:00 local = Domingo 03:00 UTC
    - cron: "0 3 * * 0"
    # Durante horario estándar Tijuana ≈ UTC-8 → 20:00 local = Domingo 04:00 UTC
    - cron: "0 4 * * 0"
  workflow_dispatch:
    inputs:
      batch:
        description: "Elegir lote a ejecutar"
        type: choice
        required: true
        default: "weekend"
        options: [tnf, weekend]

jobs:
  picks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Determina el batch según el disparador
      - name: Determine batch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BATCH=${{ inputs.batch }}" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" = "0 16 * * 4" ]; then
            echo "BATCH=tnf" >> $GITHUB_ENV
          else
            echo "BATCH=weekend" >> $GITHUB_ENV
          fi

      # Guard: solo ejecutar Weekend si es sábado 20:00 en America/Tijuana
      - name: Guard local time (Weekend only)
        id: guard
        run: |
          if [ "$BATCH" != "weekend" ]; then
            echo "run=1" >> $GITHUB_OUTPUT
            exit 0
          fi
          TZ_ID="America/Tijuana"
          DOW=$(TZ=$TZ_ID date +%u)   # 6 = sábado
          HOUR=$(TZ=$TZ_ID date +%H)  # 20 = 8pm
          echo "Local America/Tijuana → DOW=$DOW HOUR=$HOUR"
          if [ "$DOW" = "6" ] && [ "$HOUR" = "20" ]; then
            echo "run=1" >> $GITHUB_OUTPUT
          else
            echo "run=0" >> $GITHUB_OUTPUT
          fi

      - name: Run notifier
        if: ${{ steps.guard.outputs.run == '1' || github.event_name == 'workflow_dispatch' }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          SPORTSDATAIO_KEY:   ${{ secrets.SPORTSDATAIO_KEY }}
        run: |
          echo "Batch: $BATCH"
          python src/telegram_notifier.py --batch "$BATCH"