name: NFL Picks to Telegram

on:
  schedule:
    - cron: "0 16 * * 4"   # Jueves 09:00 Tijuana (TNF)
    - cron: "0 22 * * 5"   # Viernes 15:00 Tijuana (Weekend)
  workflow_dispatch:
    inputs:
      batch:
        description: "Elegir lote a ejecutar"
        type: choice
        required: true
        default: "weekend"
        options: [tnf, weekend]

jobs:
  picks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Determine batch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BATCH=${{ inputs.batch }}" >> $GITHUB_ENV
          elif [ "${{ github.event.schedule }}" = "0 16 * * 4" ]; then
            echo "BATCH=tnf" >> $GITHUB_ENV
          else
            echo "BATCH=weekend" >> $GITHUB_ENV
          fi

      - name: Run notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
          SPORTSDATAIO_KEY:   ${{ secrets.SPORTSDATAIO_KEY }}
        run: |
          python src/telegram_notifier.py --batch "$BATCH"
