name: NFL Picks to Telegram

on:
  schedule:
    - cron: "0 16 * * 4"   # Jueves 16:00 UTC -> 09:00 Tijuana (TNF)
    - cron: "0 22 * * 5"   # Viernes 22:00 UTC -> 15:00 Tijuana (Weekend)
  workflow_dispatch:

jobs:
  picks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: TNF batch
        if: github.event.schedule == '0 16 * * 4'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python src/telegram_notifier.py --batch tnf
      - name: Weekend batch
        if: github.event.schedule == '0 22 * * 5'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python src/telegram_notifier.py --batch weekend
