name: NFL Picks to Telegram

on:
  schedule:
    - cron: "0 16 * * 4"   # Jueves 16:00 UTC -> 09:00 Tijuana (TNF)
    - cron: "0 22 * * 5"   # Viernes 22:00 UTC -> 15:00 Tijuana (Weekend)
  workflow_dispatch:
    inputs:
      batch:
        description: "Elegir lote a ejecutar"
        type: choice
        required: true
        default: "weekend"
        options:
          - tnf
          - weekend

jobs:
  picks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Decide si es ejecución manual o por cron, y fija BATCH
      - name: Determine batch
        id: setbatch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BATCH=${{ inputs.batch }}" >> $GITHUB_ENV
          else
            if [ "${{ github.event.schedule }}" = "0 16 * * 4" ]; then
              echo "BATCH=tnf" >> $GITHUB_ENV
            else
              echo "BATCH=weekend" >> $GITHUB_ENV
            fi
          fi
          echo "Batch seleccionado: $BATCH"

      # Ping de diagnóstico: confirma token+chat_id
      - name: Ping Telegram (debug)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="Ping desde GitHub Actions ✅"

      # Prueba de envío desde Python (por si curl fallara)
      - name: Smoke test - mensaje Python (debug)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - << 'PY'
          import os, requests
          url=f"https://api.telegram.org/bot{os.environ['TELEGRAM_BOT_TOKEN']}/sendMessage"
          r=requests.post(url, data={"chat_id":os.environ["TELEGRAM_CHAT_ID"],"text":"✅ Test directo desde Python"})
          print("HTTP", r.status_code, r.text)
          r.raise_for_status()
          PY

      # Envío real de picks
      - name: Run notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          ODDS_API_KEY:       ${{ secrets.ODDS_API_KEY }}
        run: |
          python src/telegram_notifier.py --batch "$BATCH"
